### ISSUE TITLE
Getting Error When Install Ryft SDK in Xcode 16

### ISSUE THREAD

**Issue by rushabh0999** [RyftPay/ryft-ios#19]
Hello Team,
I am using Ryft iOS SDK in my current project its working fine in Xcode 15 there is no issue in Xcode 15 but When Run my existing project in Xcode 16 at that Ryft  iOS SDK giving me error.I have attached screenshot here.Please help me to resolve this issue.I am using the latest Ryft SDK version in my project.
![WhatsApp Image 2024-10-09 at 21 45 36](https://github.com/user-attachments/assets/b809300c-00fc-4294-b7b5-92db982eaf1c)

**Comment by ryft-rkirby** [comment]
Hi @rushabh0999, this has now been resolved as of the following release ([#1.6.1](https://github.com/RyftPay/ryft-ios/releases/tag/1.6.1))
